version: '3.8'
services:
  postgres-container:
    image: postgres:15
    environment:
      POSTGRES_DB: kitchensink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres-net
    ports:
      - "5432:5432"

  springboot-container:
    build: .
    depends_on:
      - postgres-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/kitchensink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - spring-boot-postgres-net
    ports:
      - "8080:8080"

networks:
  spring-boot-postgres-net:

volumes:
  postgres-data:
